version: "3.9"

services:
  backend:
    build: .
    command: npm run dev            # Run app in dev mode with nodemon
    ports:
      - "3001:3001"                # Host : Container
    volumes:
      - .:/app                      # Mount your project folder for live reload
      - node_modules:/app/node_modules 
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

#   mysql:
#     image: mysql:8
#     ports:
#       - "3306:3306"                 # Optional: connect via host GUI
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: app_db
#     volumes:
#       - mysql_data:/var/lib/mysql   # Persistent DB storage

volumes:
    node_modules:
#   mysql_data:
